all:
  children:
    k3s_servers:
      hosts:
        rpi-0:
          ansible_host: 192.168.50.20
          node_ip: 192.168.50.20
        rpi-1:
          ansible_host: 192.168.50.21
          node_ip: 192.168.50.21
        rpi-2:
          ansible_host: 192.168.50.22
          node_ip: 192.168.50.22

    k3s_agents:
      hosts:
        rpi-3:
          ansible_host: 192.168.50.23
          node_ip: 192.168.50.23
        rpi-4:
          ansible_host: 192.168.50.24
          node_ip: 192.168.50.24
        rpi-5:
          ansible_host: 192.168.50.25
          node_ip: 192.168.50.25

    rpi_cluster:
      children:
        k3s_servers:
        k3s_agents:
