---
expected_node_count: "{{ groups['rpi_cluster'] | length }}"

server_node_labels:
  - "node-role.kubernetes.io/control-plane=true"
  - "storage=nvme"
  - "node.kubernetes.io/storage=nvme"

agent_node_labels:
  - "node-role.kubernetes.io/worker=true"
  - "storage=nvme"
  - "node.kubernetes.io/storage=nvme"
